 // const mealPlan = {
  //   day1: {
  //     breakfast: {
  //       meal: "Oatmeal with protein powder, banana, and nuts",
  //       calories: 450,
  //       protein: 30,
  //       carbs: 60,
  //       fats: 15,
  //     },
  //     lunch: {
  //       meal: "Chicken breast sandwich on whole wheat bread with avocado and a side of sweet potato fries",
  //       calories: 600,
  //       protein: 40,
  //       carbs: 70,
  //       fats: 20,
  //     },
  //     dinner: {
  //       meal: "Salmon with quinoa and steamed broccoli",
  //       calories: 700,
  //       protein: 50,
  //       carbs: 60,
  //       fats: 30,
  //     },
  //     snacks: {
  //       meal: "Protein shake with milk and peanut butter, Greek Yogurt with berries",
  //       calories: 550,
  //       protein: 40,
  //       carbs: 40,
  //       fats: 20,
  //     },
  //     calories: 2300,
  //     protein: 160,
  //     carbs: 230,
  //     fats: 85,
  //   },
  //   day2: {
  //     breakfast: {
  //       meal: "Scrambled eggs (3) with cheese and whole wheat toast with avocado",
  //       calories: 400,
  //       protein: 25,
  //       carbs: 30,
  //       fats: 20,
  //     },
  //     lunch: {
  //       meal: "Lentil soup with a whole-wheat roll and grilled cheese sandwich",
  //       calories: 550,
  //       protein: 30,
  //       carbs: 70,
  //       fats: 15,
  //     },
  //     dinner: {
  //       meal: "Beef stir-fry with brown rice and mixed vegetables",
  //       calories: 750,
  //       protein: 55,
  //       carbs: 75,
  //       fats: 30,
  //     },
  //     snacks: {
  //       meal: "Cottage cheese with pineapple, Handful of almonds",
  //       calories: 600,
  //       protein: 40,
  //       carbs: 45,
  //       fats: 30,
  //     },
  //     calories: 2300,
  //     protein: 150,
  //     carbs: 220,
  //     fats: 95,
  //   },
  //   day3: {
  //     breakfast: {
  //       meal: "Protein pancakes (made with protein powder and oats) with syrup and fruit",
  //       calories: 500,
  //       protein: 35,
  //       carbs: 65,
  //       fats: 10,
  //     },
  //     lunch: {
  //       meal: "Tuna salad sandwich on whole wheat bread with a side of carrots",
  //       calories: 550,
  //       protein: 35,
  //       carbs: 60,
  //       fats: 20,
  //     },
  //     dinner: {
  //       meal: "Chicken parmesan with whole wheat pasta and a side salad",
  //       calories: 700,
  //       protein: 50,
  //       carbs: 70,
  //       fats: 30,
  //     },
  //     snacks: {
  //       meal: "Hard-boiled eggs (2), Banana with peanut butter",
  //       calories: 550,
  //       protein: 35,
  //       carbs: 50,
  //       fats: 25,
  //     },
  //     calories: 2300,
  //     protein: 155,
  //     carbs: 245,
  //     fats: 85,
  //   },
  //   day4: {
  //     breakfast: {
  //       meal: "Smoothie with protein powder, spinach, banana, and milk",
  //       calories: 400,
  //       protein: 30,
  //       carbs: 45,
  //       fats: 10,
  //     },
  //     lunch: {
  //       meal: "Leftover chicken parmesan with whole wheat pasta",
  //       calories: 600,
  //       protein: 45,
  //       carbs: 65,
  //       fats: 25,
  //     },
  //     dinner: {
  //       meal: "Lean ground beef tacos with whole wheat tortillas, cheese, and salsa",
  //       calories: 700,
  //       protein: 50,
  //       carbs: 60,
  //       fats: 30,
  //     },
  //     snacks: {
  //       meal: "Protein bar, Apple with almond butter",
  //       calories: 600,
  //       protein: 40,
  //       carbs: 50,
  //       fats: 30,
  //     },
  //     calories: 2300,
  //     protein: 165,
  //     carbs: 220,
  //     fats: 95,
  //   },
  //   day5: {
  //     breakfast: {
  //       meal: "Greek yogurt with granola and berries",
  //       calories: 450,
  //       protein: 25,
  //       carbs: 55,
  //       fats: 15,
  //     },
  //     lunch: {
  //       meal: "Turkey breast wrap with hummus and vegetables on a whole wheat tortilla",
  //       calories: 500,
  //       protein: 30,
  //       carbs: 50,
  //       fats: 20,
  //     },
  //     dinner: {
  //       meal: "Pork chops with mashed sweet potatoes and green beans",
  //       calories: 700,
  //       protein: 50,
  //       carbs: 60,
  //       fats: 30,
  //     },
  //     snacks: {
  //       meal: "Trail mix, String cheese",
  //       calories: 650,
  //       protein: 45,
  //       carbs: 55,
  //       fats: 35,
  //     },
  //     calories: 2300,
  //     protein: 150,
  //     carbs: 220,
  //     fats: 100,
  //   },
  //   day6: {
  //     breakfast: {
  //       meal: "Waffles with peanut butter and banana",
  //       calories: 500,
  //       protein: 20,
  //       carbs: 70,
  //       fats: 20,
  //     },
  //     lunch: {
  //       meal: "Chicken salad sandwich on whole wheat bread with a side of fruit salad",
  //       calories: 550,
  //       protein: 30,
  //       carbs: 65,
  //       fats: 20,
  //     },
  //     dinner: {
  //       meal: "Pizza with whole wheat crust, lots of veggies, and lean protein (chicken or turkey)",
  //       calories: 650,
  //       protein: 40,
  //       carbs: 70,
  //       fats: 25,
  //     },
  //     snacks: {
  //       meal: "Rice cakes with avocado, Glass of milk",
  //       calories: 600,
  //       protein: 30,
  //       carbs: 60,
  //       fats: 30,
  //     },
  //     calories: 2300,
  //     protein: 120,
  //     carbs: 265,
  //     fats: 95,
  //   },
  // }